models/School.php
<?php

namespace app\models;

use yii\db\ActiveQueryInterface;
use yii\db\ActiveRecord;

class School extends ActiveRecord
{
    public function rules(): array
    {
        return [
            [['school'], 'required']
        ];
    }

    public function getStudents(): ActiveQueryInterface
    {
        return $this->hasMany(Student::class, ['school_id' => 'id']);
    }
}

controllers/SchoolController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\School;
use app\models\Student;

class SchoolController extends Controller
{
    private array $homeUrl = ['index'];

    public function actionIndex(): string
    {
        $query = School::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $schools = $query->orderBy('school')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('school-list', [
            'schools' => $schools,
            'pagination' => $pagination
        ]);
    }

    public function actionAdd(): string|\yii\web\Response
    {
        $model = new School();

        if (
            $model->load(Yii::$app->request->post()) &&
            $model->validate() &&
            $model->save()
        ) {
            return $this->redirect($this->homeUrl);
        }

        return $this->renderAjax('school-input', ['model' => $model]);
    }

    public function actionEdit(string $id): string|\yii\web\Response
    {
        $model = School::find()->where(['id' => $id])->one();
        if (
            $model->load(Yii::$app->request->post()) &&
            $model->validate() &&
            $model->save()
        ) {
            return $this->redirect($this->homeUrl);
        }

        return $this->render('school-input', ['model' => $model]);
    }

    public function actionDelete(string $id): string|\yii\web\Response
    {

        $school = School::findOne($id);

        if ($school->getStudents()->count() > 0) {
            return 'ERROR - First you need delete student from class!';
        }
        $school->delete();

        return $this->redirect($this->homeUrl);
    }

}

controllers/StudentController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Student;
use yii\data\Pagination;
use Yii;

class StudentController extends Controller
{
    protected array $homeUrl = ['index'];

    public function actionIndex(): string
    {
        $query = Student::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $student = $query
            ->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('student-list', [
            'student' => $student,
            'pagination' => $pagination
        ]);
    }

    public function actionAdd(): string|\yii\web\Response
    {
        $model = new Student();

        if (
            $model->load(Yii::$app->request->post()) &&
            $model->validate() &&
            $model->save()
        ) {
            return $this->redirect($this->homeUrl);
        }

        return $this->renderAjax('student-input', [
            'model' => $model,
        ]);
    }

    public function actionEdit(string $id): string|\yii\web\Response
    {
        $model = Student::find()->where(['id' => $id])->one();

        if (
            $model->load(Yii::$app->request->post()) &&
            $model->validate() &&
            $model->save()
        ) {
            return $this->redirect($this->homeUrl);
        }

        return $this->render('student-input', ['model' => $model]);
    }

    public function actionDelete(string $id): \yii\web\Response
    {
        $student = Student::findOne($id);
        $student->delete();

        return $this->redirect($this->homeUrl);
    }

    public function actionSort($id): string
    {

        $query = Student::find()
            ->where(['school_id' => $id]);

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count()
        ]);

        $student = $query
            ->orderBy('name')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('student-list', [
            'student' => $student,
            'pagination' => $pagination
        ]);

    }
}

views/school/school-input.php
<?php
/**
 * @var \app\models\School $model
 */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php ActiveForm::$autoIdPrefix = 'a'; ?>
<?php $form = ActiveForm::begin(); ?>

<?= $form->field($model, 'school') ?>
    <div class="form-group">
        <?= Html::submitButton(empty($model->id) ? 'Create' : 'Update', ['class' => 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>

views/school/school-list.php
<?php
/**
 * @var array $schools
 * @var string $pagination
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
use lav45\widget\AjaxCreate;

?>
    <h1>Classes</h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name of class</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach ($schools as $school): ?>
            <tr>
                <td><?= Html::encode("{$school->id}") ?></td>
                <td><?= Html::encode("{$school->school}") ?></td>
                <td>
                    <?= Html::a('Change', ['edit', 'id' => $school->id], ['class' => 'btn btn-primary']) ?>
                    <?php
                    AjaxCreate::begin();

                    echo Html::button('Delete', [
                        'data-href' => Url::toRoute(['delete', 'id' => $school->id]),
                        'class' => 'btn btn-danger',
                    ]);

                    AjaxCreate::end();
                    ?>
                    <?= Html::a('Select', ['student/sort', 'id' => $school->id], ['class' => 'btn btn-primary']) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>


<?= LinkPager::widget(['pagination' => $pagination]) ?>

<?php
AjaxCreate::begin();

echo Html::button('Create class', [
    'data-href' => Url::toRoute(['add']),
    'class' => 'btn btn-success',
]);

AjaxCreate::end();
?>